### ISSUE TITLE
Make `Struct discord::State` be default-constructed

### ISSUE THREAD

**Issue by iddm** [SpaceManiac/discord-rs#38]
In many cases we need to store `State` object inside the structure to access it from different places. But we unable to do that because it needs to be constructed with `ReadyEvent` but we may not have it in our struct's constructor yet.

Currently to store it we have to create a fake `ReadyEvent`:

``` rust
// TODO remove when discord::State will have default ctor
fn get_fake_ready_event() -> ReadyEvent {
    ReadyEvent {
        version: 0,
        user: CurrentUser {
            id: UserId(0),
            username: String::default(),
            discriminator: String::default(),
            avatar: None,
            email: None,
            verified: false,
            bot: false,
            mfa_enabled: false
        },
        session_id: String::default(),
        heartbeat_interval: 0,
        user_settings: None,
        read_state: None,
        private_channels: Vec::default(),
        presences: Vec::default(),
        relationships: Vec::default(),
        servers: Vec::default(),
        user_server_settings: None,
        tutorial: None,
        trace: Vec::default(),
    }
}
```

This is not good.

**Comment by SpaceManiac** [comment]
While your solution is a little unclean, I think it's even less clean to make it _normal_ for `State` to be constructed without a valid `ReadyEvent`, rather than a quirk of certain client architectures. Keep using your current solution or rearrange your initialization process so that your `struct` is only constructed after a `ReadyEvent` is available.
